const produtos=[
{id:1,nome:"Baião de Dois",categoria:"Pratos",preco:24.9,descricao:"Arroz, feijão-de-corda, queijo coalho e carne-seca.",imagem:"🍛",disponivel:true},
{id:2,nome:"Carne de Sol",categoria:"Pratos",preco:29.9,descricao:"Carne de sol acebolada, mandioca e vinagrete.",imagem:"🥩",disponivel:true},
{id:3,nome:"Cuscuz Nordestino",categoria:"Pratos",preco:16.9,descricao:"Cuscuz de milho com queijo e manteiga de garrafa.",imagem:"🌽",disponivel:true},
{id:4,nome:"Tapioca de Queijo",categoria:"Lanches",preco:12.9,descricao:"Tapioca feita na hora com queijo coalho.",imagem:"🫓",disponivel:true},
{id:5,nome:"Caldo de Sururu",categoria:"Pratos",preco:18.9,descricao:"Caldo temperado servido quente.",imagem:"🥣",disponivel:true},
{id:6,nome:"Suco de Caju",categoria:"Bebidas",preco:8.9,descricao:"Suco de caju gelado.",imagem:"🥤",disponivel:true},
{id:7,nome:"Bolo de Milho",categoria:"Lanches",preco:9.9,descricao:"Fatia de bolo de milho caseiro.",imagem:"🍰",disponivel:false}
];
const unidades=[{nome:"Centro",endereco:"Rua Principal, 120",distancia:"1,8 km"},{nome:"Jardins",endereco:"Av. das Palmeiras, 480",distancia:"4,2 km"},{nome:"Shopping",endereco:"Praça de Alimentação, piso 2",distancia:"6,7 km"}];
const campanhas=[{titulo:"Baião + bebida",texto:"Baião de Dois + Suco de Caju por R$ 29,90.",regra:"Válida na unidade selecionada enquanto houver disponibilidade."},{titulo:"Raízes+",texto:"A cada compra elegível, o cliente acumula pontos.",regra:"200 pontos podem ser trocados por R$ 10 de desconto."},{titulo:"Terça da Tapioca",texto:"10% de desconto em tapiocas às terças-feiras.",regra:"Campanha demonstrativa; condições definidas pela unidade."},{titulo:"Semana Nordestina",texto:"Benefício especial para clientes cadastrados.",regra:"Comunicação promocional depende de consentimento de marketing."}];
let carrinho=[];let produtoAtual=null;let filtroAtual="Todos";let pedido=null;let statusIndex=2;let pontos=120;
const dinheiro=v=>v.toLocaleString("pt-BR",{style:"currency",currency:"BRL"});
const tela=n=>{document.querySelectorAll(".tela").forEach(x=>x.classList.remove("ativa"));const el=document.getElementById(n);if(el)el.classList.add("ativa");window.scrollTo(0,0);if(n==="carrinho")atualizarCarrinho()};
function montarProdutos(){const lista=filtroAtual==="Todos"?produtos:produtos.filter(p=>p.categoria===filtroAtual);document.getElementById("lista-produtos").innerHTML=lista.map(card).join("");document.getElementById("destaques").innerHTML=produtos.filter(p=>p.disponivel).slice(0,3).map(card).join("");document.querySelectorAll(".produto").forEach(e=>e.onclick=()=>abrirProduto(+e.dataset.id));}
function card(p){return `<article class="produto" data-id="${p.id}"><div class="produto-imagem">${p.imagem}</div><div class="produto-info"><h3>${p.nome}</h3><p>${p.descricao}</p><span class="preco">${dinheiro(p.preco)}</span>${p.disponivel?"":"<p><b>Indisponível no momento</b></p>"}</div></article>`}
function montarUnidades(){document.getElementById("lista-unidades").innerHTML=unidades.map((u,i)=>`<button class="unidade-opcao" data-u="${i}"><div><b>Raízes do Nordeste - ${u.nome}</b><p>${u.endereco} · ${u.distancia}</p></div><span class="aberta">Aberta</span></button>`).join("");document.querySelectorAll("[data-u]").forEach(b=>b.onclick=()=>{const u=unidades[+b.dataset.u];document.getElementById("unidade-home").textContent=u.nome;document.getElementById("endereco-home").textContent=`${u.endereco} · ${u.distancia}`;document.getElementById("pedido-unidade").textContent=`Retirada no balcão · ${u.nome}`;tela("cardapio")})}
function abrirProduto(id){produtoAtual=produtos.find(p=>p.id===id);document.getElementById("produto-detalhe").innerHTML=`<div class="produto-detalhe"><div class="imagem">${produtoAtual.imagem}</div><h1>${produtoAtual.nome}</h1><p>${produtoAtual.descricao}</p><h2>${dinheiro(produtoAtual.preco)}</h2><p class="cinza">Quantidade: 1</p><button class="btn largo" id="adicionar" ${produtoAtual.disponivel?"":"disabled"}>${produtoAtual.disponivel?"Adicionar ao carrinho":"Produto indisponível"}</button></div>`;document.getElementById("adicionar").onclick=()=>{carrinho.push(produtoAtual);atualizarQuantidade();tela("cardapio")};tela("produto")}
function atualizarQuantidade(){document.getElementById("qtd-carrinho").textContent=carrinho.length}
function total(){return carrinho.reduce((s,p)=>s+p.preco,0)}
function atualizarCarrinho(){atualizarQuantidade();const area=document.getElementById("itens-carrinho"),botao=document.getElementById("ir-pagamento");if(!carrinho.length){area.innerHTML=`<div class="resumo"><b>O carrinho está vazio.</b><p class="cinza">Adicione um produto para continuar.</p></div>`;botao.disabled=true;return}area.innerHTML=carrinho.map((p,i)=>`<div class="item-carrinho"><div><b>${p.nome}</b><small>${dinheiro(p.preco)}</small></div><button class="remover" data-remover="${i}">remover</button></div>`).join("")+`<div class="resumo"><div><span>Itens</span><b>${carrinho.length}</b></div><div><span>Total</span><b>${dinheiro(total())}</b></div></div>`;botao.disabled=false;document.querySelectorAll("[data-remover]").forEach(b=>b.onclick=()=>{carrinho.splice(+b.dataset.remover,1);atualizarCarrinho()})}
function prepararPagamento(){if(!carrinho.length){document.getElementById("pagamento-erro").textContent="Adicione pelo menos um produto antes de continuar.";document.getElementById("pagamento-erro").classList.remove("oculto");return}document.getElementById("resumo-pagamento").innerHTML=`<div><span>Itens</span><b>${carrinho.length}</b></div><div><span>Total</span><b>${dinheiro(total())}</b></div>`;document.getElementById("pagamento-erro").classList.add("oculto");tela("pagamento")}
function pagar(){if(!carrinho.length)return;document.getElementById("pagamento-erro").classList.add("oculto");tela("processando");setTimeout(()=>{if(document.getElementById("simular-falha").checked){tela("pagamento");const e=document.getElementById("pagamento-erro");e.textContent="Não foi possível concluir o pagamento. O serviço externo não respondeu. Tente novamente ou escolha outra forma de pagamento.";e.classList.remove("oculto");return}const numero="#RN-"+(Math.floor(Math.random()*9000)+1000);pedido={numero,status:"Em preparo",forma:document.querySelector('input[name="pagamento"]:checked').value,total:total()};statusIndex=2;document.getElementById("numero-pedido").textContent=`Pedido ${numero} · retirada no balcão`;document.getElementById("pedido-acompanhamento").textContent=numero;document.getElementById("pedido-unidade").textContent=`Retirada no balcão · ${document.getElementById("unidade-home").textContent}`;carrinho=[];atualizarQuantidade();tela("sucesso")},1100)}
function atualizarStatus(){if(!pedido)return;statusIndex=Math.min(statusIndex+1,4);const itens=document.querySelectorAll(".etapas>div");itens.forEach((el,i)=>{el.classList.toggle("feito",i<statusIndex);el.classList.toggle("atual",i===statusIndex)});const nomes=["Pedido recebido","Pagamento aprovado","Em preparo","Pronto","Retirado"];pedido.status=nomes[statusIndex]||"Retirado";document.getElementById("avancar-status").textContent=statusIndex>=4?"Pedido finalizado":"Simular avanço do pedido"}
function renderCampanhas(){document.getElementById("lista-campanhas").innerHTML=campanhas.map(c=>`<article class="campanha"><strong>${c.titulo}</strong><h3>${c.texto}</h3><p class="cinza">${c.regra}</p></article>`).join("")}
function renderPontos(){document.getElementById("pontos-total").textContent=pontos;document.getElementById("home-pontos").textContent=pontos;document.getElementById("barra-pontos").style.width=Math.min(pontos/200*100,100)+"%"}
function entrar(){const email=document.getElementById("login-email").value.trim(),senha=document.getElementById("login-senha").value,erro=document.getElementById("login-erro");if(email!=="joao@raizes.local"||senha!=="123456"){erro.textContent="E-mail ou senha inválidos. Use os dados de demonstração informados abaixo.";erro.classList.remove("oculto");return}document.getElementById("nome-conta").textContent="João da Silva";document.getElementById("email-conta").textContent=email;erro.classList.add("oculto");tela("conta")}
function criarConta(){const n=document.getElementById("cadastro-nome").value.trim(),e=document.getElementById("cadastro-email").value.trim(),s=document.getElementById("cadastro-senha").value,c=document.getElementById("cadastro-consentimento").checked,erro=document.getElementById("cadastro-erro");if(!n||!e||s.length<6||!c){erro.textContent="Preencha nome, e-mail, senha de pelo menos 6 caracteres e aceite o uso dos dados necessários.";erro.classList.remove("oculto");return}erro.classList.add("oculto");document.getElementById("nome-conta").textContent=n;document.getElementById("email-conta").textContent=e;document.getElementById("marketing").checked=document.getElementById("cadastro-marketing").checked;tela("conta")}
function recuperar(){const e=document.getElementById("recuperar-email").value.trim(),m=document.getElementById("recuperar-msg");if(!e||!e.includes("@")){m.textContent="Informe um e-mail válido.";m.classList.remove("oculto");return}m.textContent="Instruções simuladas enviadas para o e-mail informado.";m.classList.remove("oculto")}

document.addEventListener("click",ev=>{const b=ev.target.closest("[data-tela]");if(b){ev.preventDefault();tela(b.dataset.tela)}const r=ev.target.closest("[data-recompensa]");if(r){const custo=r.dataset.recompensa==="10"?200:300;if(pontos<custo){alert("Você ainda não tem pontos suficientes para essa recompensa.");return}pontos-=custo;renderPontos();alert("Recompensa resgatada na simulação.")}});
document.querySelectorAll(".filtro").forEach(b=>b.onclick=()=>{document.querySelectorAll(".filtro").forEach(x=>x.classList.remove("selecionado"));b.classList.add("selecionado");filtroAtual=b.dataset.filtro;montarProdutos()});
document.getElementById("ir-pagamento").onclick=prepararPagamento;document.getElementById("pagar").onclick=pagar;document.getElementById("entrar").onclick=entrar;document.getElementById("criar-conta").onclick=criarConta;document.getElementById("recuperar-btn").onclick=recuperar;document.getElementById("avancar-status").onclick=atualizarStatus;document.getElementById("sair").onclick=()=>tela("inicio");
document.querySelectorAll("[data-role]").forEach(b=>b.onclick=()=>{const textos={atendente:"Atendente: consulta o pedido, confirma pagamento e registra a retirada.",cozinha:"Cozinha: recebe o pedido aprovado e atualiza preparo/pronto.",gerente:"Gerente: acompanha indicadores da unidade e campanhas ativas."};document.getElementById("role-result").innerHTML=`<b>${b.textContent}</b><p>${textos[b.dataset.role]}</p>`});
document.getElementById("canal").onchange=e=>document.body.dataset.canal=e.target.value;
montarProdutos();montarUnidades();renderCampanhas();renderPontos();atualizarQuantidade();
